// Route (level) definitions. Everything visual and gameplay-related that varies
// between the four runs lives here.
import * as THREE from 'three';

const C = (hex) => new THREE.Color(hex);

export const ROUTES = [
  {
    id: 'plains',
    name: 'Dry Creek Plains',
    from: 'Mercy Springs', to: 'Dry Creek',
    blurb: 'Open grassland at golden hour. Riders will try to run you down.',
    seed: 1871, length: 2600, biome: 'plains', reward: 400,
    wind: 0.9, winding: 0.35,
    light: {
      sunElev: 13, sunAzim: 230, sunColor: C('#ffc98a'), sunIntensity: 4.2,
      hemiSky: C('#7f9fd0'), hemiGround: C('#5a3f24'), hemiIntensity: 0.7, env: 0.3, tintShadow: [0.8, 0.9, 1.12],
      zenith: C('#3f6ea8'), horizon: C('#f2c18c'), sunGlow: C('#ffb36b'), ground: C('#8a6a45'),
      fog: C('#d8b48c'), fogDensity: 0.0017, exposure: 0.95, clouds: 0.45,
      grade: { sat: 1.08, contrast: 1.15, gain: [1.04, 1.0, 0.92], lift: [0.008, 0.004, 0.0] },
    },
    terrain: {
      ground1: 'dry_grass', ground2: 'green_grass', road: 'dirt_road', rock: 'rock', snow: null,
      tint1: C('#ffffff'), tint2: C('#fff6c8'), rockTint: C('#c8b8a0'), roadTint: C('#fff4e6'), propRock: C('#d8c8b0'),
      snowLine: 9999, blend: 34, rockSlope: 0.2, greenMix: [0.5, 0.75],
    },
    scatter: [
      { kind: 'Sagebrush', density: 22, minRoad: 7, cluster: 0.1, scale: [0.8, 1.5] },
      { kind: 'Rock_A', density: 1.6, minRoad: 8, scale: [0.6, 1.8] },
      { kind: 'Rock_B', density: 1.2, minRoad: 8, scale: [0.6, 1.6] },
      { kind: 'Boulder_Big', density: 0.25, minRoad: 25, scale: [0.8, 1.6], far: true },
      { kind: 'Pine_A', density: 0.7, minRoad: 25, cluster: 0.45, scale: [0.9, 1.4], far: true },
      { kind: 'DeadTree', density: 0.25, minRoad: 10, scale: [0.9, 1.3], far: true },
      { kind: 'Fence_Rail', density: 0, fence: true },
      { kind: 'TelegraphPole', density: 0, poles: true },
      { kind: 'CowSkull', density: 0.1, minRoad: 5, scale: [1, 1] },
    ],
    grass: { density: 3.5, color: C('#c9a860'), height: 0.42 },
    wildlife: { kinds: ['buffalo', 'buffalo', 'goat', 'goat', 'hawk'], every: 105 },
    railroad: { at: 0.62, workers: 7 },
    waves: [
      { at: 0.08, type: 'riders', count: 2, from: 'behind' },
      { at: 0.2, type: 'riders', count: 3, from: 'flank' },
      { at: 0.28, type: 'herd', count: 16, kind: 'buffalo', lead: 320 },
      { at: 0.34, type: 'ridge', count: 2 },
      { at: 0.42, type: 'riders', count: 4, from: 'behind' },
      { at: 0.58, type: 'riders', count: 3, from: 'ahead' },
      { at: 0.66, type: 'ridge', count: 3 },
      { at: 0.76, type: 'riders', count: 5, from: 'behind' },
    ],
  },
  {
    id: 'pass',
    name: "Widow's Pass",
    from: 'Dry Creek', to: 'Silver Notch',
    blurb: 'A winding mountain road. Riflemen on every ridge; mind the drop.',
    seed: 1874, length: 2800, biome: 'mountain', reward: 650,
    wildlife: { kinds: ['goat', 'goat', 'goat', 'bear', 'hawk'], every: 120 },
    wind: 1.2, winding: 1.0,
    light: {
      sunElev: 24, sunAzim: 150, sunColor: C('#ffe2c0'), sunIntensity: 3.0,
      hemiSky: C('#9fb4d2'), hemiGround: C('#4d4a40'), hemiIntensity: 0.85, env: 0.35, tintShadow: [0.8, 0.9, 1.12],
      zenith: C('#4a6a92'), horizon: C('#b9c3cc'), sunGlow: C('#c9bba0'), ground: C('#5a5850'),
      fog: C('#8e9cae'), fogDensity: 0.0019, exposure: 1.0, clouds: 0.75,
      grade: { sat: 0.95, contrast: 1.14, gain: [0.98, 1.0, 1.04], lift: [0.0, 0.004, 0.012] },
    },
    terrain: {
      ground1: 'green_grass', ground2: 'dry_grass', road: 'dirt_road', rock: 'rock', snow: 'snow',
      tint1: C('#b9c29a'), tint2: C('#c9b48a'), rockTint: C('#b0aca6'), roadTint: C('#d8d0c4'), propRock: C('#b8b4ae'),
      snowLine: 122, blend: 20, rockSlope: 0.2,
    },
    scatter: [
      { kind: 'Pine_A', density: 40, minRoad: 7, cluster: 0.25, scale: [0.9, 1.5], far: true, maxH: 118 },
      { kind: 'Pine_B', density: 26, minRoad: 7, cluster: 0.3, scale: [0.9, 1.4], far: true, maxH: 118 },
      { kind: 'Pine_Snow', density: 20, minRoad: 7, cluster: 0.2, scale: [0.9, 1.4], far: true, minH: 105, maxH: 170 },
      { kind: 'Rock_A', density: 3, minRoad: 6, scale: [0.6, 2.2] },
      { kind: 'Rock_C', density: 2, minRoad: 6, scale: [0.8, 2.0] },
      { kind: 'Boulder_Big', density: 0.8, minRoad: 12, scale: [0.8, 2.0], far: true },
      { kind: 'CliffChunk', density: 0.5, minRoad: 14, scale: [1, 2], far: true, minSlope: 0.3 },
      { kind: 'Sagebrush', density: 6, minRoad: 6, scale: [0.6, 1.1], maxH: 110 },
      { kind: 'DeadTree', density: 0.3, minRoad: 8, scale: [0.9, 1.2], far: true },
    ],
    grass: { density: 0.8, color: C('#9aa060'), height: 0.45 },
    waves: [
      { at: 0.07, type: 'ridge', count: 2 },
      { at: 0.16, type: 'riders', count: 2, from: 'behind' },
      { at: 0.27, type: 'ridge', count: 3 },
      { at: 0.38, type: 'riders', count: 3, from: 'ahead' },
      { at: 0.5, type: 'ridge', count: 3 },
      { at: 0.6, type: 'riders', count: 4, from: 'behind' },
      { at: 0.72, type: 'ridge', count: 4 },
      { at: 0.82, type: 'riders', count: 4, from: 'flank' },
    ],
  },
  {
    id: 'perdition',
    name: 'Perdition',
    from: 'Silver Notch', to: 'Red Mesa',
    blurb: 'Straight through a ghost town at dusk. Gunmen in every window.',
    seed: 1877, length: 2400, biome: 'desert', reward: 900,
    wildlife: { kinds: ['goat', 'goat', 'hawk'], every: 130 },
    railroad: { at: 0.34, workers: 5 },
    wind: 1.0, winding: 0.25,
    ghostTown: { start: 0.38, length: 420 },
    light: {
      sunElev: 5, sunAzim: 260, sunColor: C('#ff9a55'), sunIntensity: 3.0,
      hemiSky: C('#7d7fa8'), hemiGround: C('#6a4630'), hemiIntensity: 1.0,
      zenith: C('#2e3f6e'), horizon: C('#f08a55'), sunGlow: C('#ff7a3a'), ground: C('#6a4a32'),
      fog: C('#c98a66'), fogDensity: 0.0021, exposure: 1.1, clouds: 0.55,
      grade: { sat: 1.12, contrast: 1.1, gain: [1.06, 0.97, 0.9], lift: [0.02, 0.006, 0.012] }, tintShadow: [0.8, 0.9, 1.12],
    },
    terrain: {
      ground1: 'sand', ground2: 'dry_grass', road: 'dirt_road', rock: 'red_rock', snow: null,
      tint1: C('#f0d8b8'), tint2: C('#c8a070'), rockTint: C('#e0b090'), roadTint: C('#f0c8a0'), propRock: C('#e8b090'),
      snowLine: 9999, blend: 30,
    },
    scatter: [
      { kind: 'Saguaro', density: 1.4, minRoad: 8, scale: [0.8, 1.4], far: true },
      { kind: 'Joshua', density: 0.8, minRoad: 8, scale: [0.8, 1.3], far: true },
      { kind: 'Sagebrush', density: 12, minRoad: 6, scale: [0.6, 1.2] },
      { kind: 'Rock_B', density: 1.5, minRoad: 7, scale: [0.6, 1.8] },
      { kind: 'Boulder_Big', density: 0.4, minRoad: 20, scale: [0.8, 1.8], far: true },
      { kind: 'Tumbleweed', density: 0.4, minRoad: 3, scale: [0.8, 1.2] },
      { kind: 'CowSkull', density: 0.15, minRoad: 4, scale: [1, 1] },
      { kind: 'GraveCross', density: 0.08, minRoad: 6, scale: [1, 1] },
      { kind: 'TelegraphPole', density: 0, poles: true },
    ],
    grass: { density: 0.35, color: C('#b09060'), height: 0.4 },
    waves: [
      { at: 0.1, type: 'riders', count: 3, from: 'behind' },
      { at: 0.24, type: 'ridge', count: 2 },
      { at: 0.38, type: 'town', count: 10 },
      { at: 0.44, type: 'riders', count: 3, from: 'ahead' },
      { at: 0.66, type: 'riders', count: 4, from: 'behind' },
      { at: 0.8, type: 'ridge', count: 3 },
    ],
  },
  {
    id: 'gulch',
    name: "Devil's Gulch",
    from: 'Red Mesa', to: 'Fort Providence',
    blurb: 'A red canyon at sundown. Every gun in the territory wants your strongbox.',
    seed: 1879, length: 3000, biome: 'canyon', reward: 1400,
    wildlife: { kinds: ['bear', 'goat', 'goat', 'hawk'], every: 115 },
    wind: 1.1, winding: 0.6,
    light: {
      sunElev: 16, sunAzim: 200, sunColor: C('#ffb070'), sunIntensity: 4.2,
      hemiSky: C('#8aa2d6'), hemiGround: C('#8a4028'), hemiIntensity: 1.05, env: 0.5, tintShadow: [0.82, 0.9, 1.1],
      zenith: C('#335c96'), horizon: C('#f5b07a'), sunGlow: C('#ff9848'), ground: C('#7a4028'),
      fog: C('#c48a6a'), fogDensity: 0.0022, exposure: 1.22, clouds: 0.3,
      grade: { sat: 1.02, contrast: 1.13, gain: [1.05, 0.98, 0.9], lift: [0.018, 0.006, 0.0] },
    },
    terrain: {
      ground1: 'sand', ground2: 'gravel', road: 'dirt_road', rock: 'red_rock', snow: null,
      tint1: C('#f2c9a0'), tint2: C('#d0a080'), rockTint: C('#ffffff'), roadTint: C('#f2b88c'), propRock: C('#ffb08a'),
      snowLine: 9999, blend: 34,
    },
    scatter: [
      { kind: 'Rock_A', density: 3, minRoad: 6, scale: [0.6, 2.2] },
      { kind: 'Rock_C', density: 2, minRoad: 6, scale: [0.8, 2.0] },
      { kind: 'Boulder_Big', density: 1.0, minRoad: 10, scale: [0.8, 2.2], far: true },
      { kind: 'Sagebrush', density: 8, minRoad: 6, scale: [0.6, 1.1] },
      { kind: 'Saguaro', density: 0.5, minRoad: 10, scale: [0.8, 1.3], far: true },
      { kind: 'DeadTree', density: 0.3, minRoad: 8, scale: [0.8, 1.2], far: true },
      { kind: 'Wagon_Wreck', density: 0.04, minRoad: 6, scale: [1, 1] },
      { kind: 'CowSkull', density: 0.1, minRoad: 4, scale: [1, 1] },
    ],
    grass: { density: 0.3, color: C('#b89060'), height: 0.4 },
    waves: [
      { at: 0.06, type: 'riders', count: 3, from: 'behind' },
      { at: 0.16, type: 'ridge', count: 3 },
      { at: 0.26, type: 'riders', count: 4, from: 'flank' },
      { at: 0.38, type: 'ridge', count: 4 },
      { at: 0.48, type: 'riders', count: 5, from: 'behind' },
      { at: 0.6, type: 'ridge', count: 4 },
      { at: 0.7, type: 'riders', count: 4, from: 'ahead' },
      { at: 0.8, type: 'riders', count: 6, from: 'behind' },
      { at: 0.86, type: 'ridge', count: 4 },
    ],
  },
  {
    id: 'gorge',
    name: 'Thunder Gorge',
    from: 'Fort Providence', to: 'Cascade',
    blurb: 'A ledge blasted into the gorge wall. The road runs under the falls — go through, or go over the side.',
    seed: 1883, length: 2700, biome: 'gorge', reward: 1800,
    wind: 1.1, winding: 0.75,
    gorge: { side: 1, depth: 27, falls: { at: 0.54, drop: 34, width: 24 } },
    light: {
      sunElev: 19, sunAzim: 118, sunColor: C('#ffe6c4'), sunIntensity: 3.4,
      hemiSky: C('#93b4d6'), hemiGround: C('#3f4a3a'), hemiIntensity: 0.95, env: 0.4, tintShadow: [0.78, 0.9, 1.15],
      zenith: C('#3d6b9c'), horizon: C('#c9d7dc'), sunGlow: C('#ffd9a6'), ground: C('#4e5648'),
      fog: C('#a9bcc4'), fogDensity: 0.0021, exposure: 1.0, clouds: 0.6,
      grade: { sat: 1.1, contrast: 1.12, gain: [0.98, 1.02, 1.04], lift: [0.006, 0.01, 0.014] },
    },
    terrain: {
      ground1: 'green_grass', ground2: 'dry_grass', road: 'gravel', rock: 'rock', snow: null,
      tint1: C('#d8e8c8'), tint2: C('#fff2d0'), rockTint: C('#b8bcb4'), roadTint: C('#f0ece4'), propRock: C('#c4c8c0'),
      snowLine: 9999, blend: 20, rockSlope: 0.16, greenMix: [0.25, 0.55],
    },
    scatter: [
      { kind: 'Pine_A', density: 5.5, minRoad: 9, cluster: 0.5, scale: [0.9, 1.6] },
      { kind: 'Pine_B', density: 4.2, minRoad: 9, cluster: 0.5, scale: [0.9, 1.5] },
      { kind: 'Rock_A', density: 3.0, minRoad: 7, scale: [0.6, 1.9] },
      { kind: 'Rock_C', density: 2.2, minRoad: 7, scale: [0.6, 1.7] },
      { kind: 'Boulder_Big', density: 0.8, minRoad: 12, scale: [0.9, 1.8] },
      { kind: 'DeadTree', density: 0.4, minRoad: 10, scale: [0.9, 1.3] },
      { kind: 'Sagebrush', density: 6, minRoad: 6, cluster: 0.2, scale: [0.7, 1.2] },
      { kind: 'Fence_Rail', density: 0, fence: true },
      { kind: 'TelegraphPole', density: 0, poles: true },
    ],
    grass: { density: 2.6, color: C('#8fa864'), height: 0.36 },
    wildlife: { kinds: ['goat', 'goat', 'bear', 'hawk'], every: 110 },
    waves: [
      { at: 0.1, type: 'riders', count: 3, from: 'behind' },
      { at: 0.22, type: 'ridge', count: 3 },
      { at: 0.33, type: 'riders', count: 4, from: 'flank' },
      { at: 0.44, type: 'riders', count: 4, from: 'behind' },
      { at: 0.62, type: 'ridge', count: 3 },
      { at: 0.72, type: 'riders', count: 5, from: 'ahead' },
      { at: 0.85, type: 'riders', count: 5, from: 'behind' },
    ],
  },
];
